project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!tests"

website:
  title: quarto-exercises
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: example.qmd
        text: Example
      - href: reference.qmd
        text: Reference

