project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "index.qmd"
    - "example.qmd"
    - "reference.qmd"
    - "!tests"

website:
  title: quarto-exercises
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: example.qmd
        text: Example
      - href: reference.qmd
        text: Reference

format:
  html:
    theme:
      light: cosmo
      dark: darkly
