on:
  push:
    branches: main
  workflow_dispatch:

name: pages.yaml

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      
      - uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tinytex: true

      - name: Render site
        run: quarto render

      - name: Prepare Pages metadata
        run: |
          touch _site/.nojekyll

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: gh-pages
          folder: _site
          clean: true
          clean-exclude: CNAME
